#+TITLE: README for Vagrant dev linux box
#+AUTHOR:   Roman Shestakov
#+LANGUAGE: en

* Description

A Vagrant VM provisioned with ansible. This VM uses standard Debian
precise64 box. It could be used as a base box for certain dev projects
as it has provisioning for some basic development tools, such as emacs, tmux, etc.

* On startup the VM runs the ansible provision to install
- essential build tools.
- erlang
- python
- emacs ver. 24.4 built from sources
- dotfiles (https://github.com/RomanShestakov/dotfiles.git)
- emacs.d from https://github.com/RomanShestakov/.emacs.d.git

* Ansible setup
the directory layout and some of the setup scripts are used from : https://github.com/enginyoyen/ansible-best-practises/
* iterm2 defaults
iterm2 is a excellent terminal client for OSX but it requires changes
to the profile to make key shortcuts work correctly for emacs.  The
file with profiles defaults is stored in provision/iterm2_prefs and
could be restored with Iterm2 in Preferences -> Load Preferences from
a custom folder or URL
* Dotfiles
this configuration uses a fork of excellent collection of dotfiles -
scripts used to customize linux env
(https://github.com/mathiasbynens/dotfiles) .bash_profile is used
during login and it sources .bashrc .bashrc is read everytime a new
shell is started. This is a good place to add custom settings and it
also sources .path, .bash_prompt, .exports, .aliases, .functions,
.extra.
[[http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html][Here]] is the good explanation of bash login scripts

* How to create a base box:
https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one

- check vm from github and provision it
#+BEGIN_SRC
git clone https://github.com/RomanShestakov/vm.git
cd vm
vagrant up
#+END_SRC

- package newly provisioned box into a new base box
#+BEGIN_SRC
# package the VM into a new vagrant box.
# this will create vm.box file in the vm dir
vagrant package --output vm.box
# add the new box into Vagrant install into ~/.vagrant.d/boxes on the local host
# make sure vm.box file is removed from vm dir
vagrant box add vmbox vm.box --force
# now the vagrant config file which want to use this box on the local host
# should have a reference to it:
config.vm.box = "vmbox"
#+END_SRC

- init new Vagrant box:
#+BEGIN_SRC
# this will create a Vagrantfile in the current dir:
vagrant init vmbox
#+END_SRC
