# base.yml - play to install a VM

- name: base.yml
  hosts: all

  roles:
    - { role: ANXS.git, sudo: yes, tags: ["git"] }
    - { role: ANXS.build-essential, sudo: yes, tags: ["build-essensial"] }
    - { role: RomanShestakov.ansible-role-tmux, sudo: yes, tags: ["tmux"] }
    - { role: RomanShestakov.erlang, sudo: yes, tags: ["erlang"] }
    - { role: RomanShestakov.ansible-role-emacs, sudo: yes, tags: ["emacs"] }
