# raspberry_init.yml - play to install a raspberry

- name: raspberry_init.yml
  hosts: pis
  remote_user: pi
  sudo: yes

  roles:
    - { role: RomanShestakov.ansible-role-pi-setup, become: yes }

  post_tasks:
    - name: mount QNAP NFS
      action: mount name=/opt/dev src=192.168.1.79:/Dev fstype=nfs state=mounted
      sudo: yes
