# raspberry.yml - play to install a raspberry

- name: raspberry.yml
  hosts: pis
  remote_user: pi
  sudo: yes

  roles:
    # - { role: RomanShestakov.ansible-role-pi-setup, become: yes }
    - { role: geerlingguy.git, become: yes, tags: ["git"] }
    - { role: RomanShestakov.ansible-role-dotfiles, dotfiles_dest: "/home/pi" }
    - { role: RomanShestakov.ansible-role-tmux, become: yes, tags: ["tmux"] }
    - { role: RomanShestakov.erlang, become: yes, tags: ["erlang"] }
    - { role: RomanShestakov.ansible-role-emacs, become: yes, tags: ["emacs"] }
    - { role: ANXS.postgresql, become: yes, postgresql_apt_repository: 'deb-src http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi', tags: ["postgresql"] }
    - { role: nicholsn.miniconda, tags: ["miniconda"], miniconda_home: '/home/pi/miniconda',
    url: "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh" }
    - { role: RomanShestakov.ansible-role-conda-packages, conda_dir: '/home/pi/miniconda' }

  post_tasks:
    - name: .EMACS | get .emacs git repository
      git: repo={{ dot_emacs_repo_url }} dest="/home/pi/.emacs.d" accept_hostkey=yes
      sudo: False
    - name: mount QNAP NFS
      action: mount name=/opt/dev src={{ nfs }}:/Dev fstype=nfs opts=nolock state=mounted
      sudo: yes
