# vm.yml - play to install a VM

- name: vm.yml
  hosts: all

  pre_tasks:
    - name: install git, tmux
      sudo: true
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
      - git
      - tmux
    - name: DOTFILES | get dotfiles from git repository
      git: repo={{ dotfiles_repo_url }} dest="/tmp/dotfiles" accept_hostkey=yes
      register: dotfiles_downloaded
    - name: DOTFILES | install dotfiles
      command: ./bootstrap.sh -f chdir="/tmp/dotfiles"
      when: dotfiles_downloaded.changed

  roles:
    - { role: RomanShestakov.erlang, sudo: yes, tags: ["erlang"] }
    - { role: ANXS.python, sudo: yes, tags: ["python"] }
    - { role: RomanShestakov.ansible-role-emacs, sudo: yes, tags: ["emacs"] }
    - { role: ANXS.postgresql, sudo: yes, tags: ["postgresql"] }
    - { role: nicholsn.miniconda, sudo: yes, tags: ["miniconda"], miniconda_home: ~/miniconda }

  post_tasks:
    - name: .EMACS | get .emacs git repository
      git: repo={{ dot_emacs_repo_url }} dest="/home/vagrant/.emacs.d" accept_hostkey=yes

    - name: CONDA | install Anaconda
      conda: name=anaconda
