# vm.yml - play to install a VM

- name: vm.yml
  hosts: all

  roles:
    - { role: RomanShestakov.ansible-role-dotfiles, dotfiles_dest: "/home/vagrant" }
    - { role: nicholsn.miniconda, tags: ["miniconda"], miniconda_home: '/home/vagrant/miniconda' }
    - { role: RomanShestakov.ansible-role-conda-packages, tags: ["conda"] }

  post_tasks:
    - name: .EMACS | get .emacs git repository
      git: repo={{ dot_emacs_repo_url }} dest="/home/vagrant/.emacs.d" accept_hostkey=yes
