# vm.yml - play to install a VM

- name: vm.yml
  hosts: all

  roles:
    - { role: ANXS.git, sudo: yes, tags: ["git"] }
    - { role: RomanShestakov.ansible-role-tmux, sudo: yes, tags: ["tmux"] }
    - { role: RomanShestakov.ansible-role-dotfiles, tags: ["dotfiles"] }
    - { role: RomanShestakov.erlang, sudo: yes, tags: ["erlang"] }
    - { role: RomanShestakov.ansible-role-emacs, sudo: yes, tags: ["emacs"] }
    - { role: ANXS.postgresql, sudo: yes, tags: ["postgresql"] }
    - { role: nicholsn.miniconda, sudo: yes, tags: ["miniconda"], miniconda_home: ~/miniconda }
    - { role: RomanShestakov.ansible-role-conda-packages, sudo: yes, tags: ["conda"] }

  post_tasks:
    - name: .EMACS | get .emacs git repository
      git: repo={{ dot_emacs_repo_url }} dest="/home/vagrant/.emacs.d" accept_hostkey=yes
