# vm.yml - play to install a VM

- name: vm.yml
  hosts: all
  roles:
    - { role: ANXS.git, sudo: yes, tags: ["git"] }
    - { role: RomanShestakov.erlang, sudo: yes, tags: ["erlang"] }
    - { role: ANXS.python, sudo: yes, tags: ["python"] }
    - { role: RomanShestakov.ansible-role-emacs, sudo: yes, tags: ["emacs"] }
    - { role: ANXS.postgresql, sudo: yes, tags: ["postgresql"] }
    - { role: trinitronx.ansible-role-tmux, sudo: yes, tags: ["tmux"] }
  tasks:
  - name: .EMACS | get .emacs git repository
    git: repo={{ dot_emacs_repo_url }} dest="/home/vagrant/.emacs.d" accept_hostkey=yes
  - name: DOTFILES | get dotfiles from git repository
    git: repo={{ dotfiles_repo_url }} dest="/tmp/dotfiles" accept_hostkey=yes
    register: dotfiles_downloaded
  - name: DOTFILES | install dotfiles
    command: ./bootstrap.sh -f chdir="/tmp/dotfiles"
    when: dotfiles_downloaded.changed
