# -*- mode: puppet-mode -*-
# vi: set ft=ruby :

# Configuration for librarian-puppet. For example:

# for librarian-puppet v1
#forge "http://forge.puppetlabs.com"

# for librarian-puppet v2
forge "https://forgeapi.puppetlabs.com"

# mod "puppetlabs/git"
# mod "maestrodev/wget"
# mod "garethr/erlang"
# mod "camptocamp/archive"
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-apt'
# mod "tracywebtech/supervisor" 
# mod "puppetlabs/postgresql"
#mod "tracywebtech/pip"
#mod "saz/locales"

# mod "alphagov/puppet-curl",
#   :git => "git://github.com/alphagov/puppet-curl.git"

mod "stankevich-python",
  :git => "git://github.com/stankevich/puppet-python.git"

mod "puppet-ipython",
  :git => "git://github.com/RomanShestakov/puppet-ipython.git"


