# file: erlang/tasks/source.yml

- name: ensure emacs repository is registered
  sudo: true
  action: apt_repository repo=ppa:cassou/emacs

- name: Erlang | Make sure the build dependencies are installed
  sudo: true
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - build-essential
    - git-core
    - python-software-properties
    - curl
    - libncurses5-dev
    - openssl
    - libssl-dev
    - fop
    - autotools-dev
    - automake
    - libproc-dev

- name: Emacs install
  sudo: true
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - emacs24
    - emacs24-el
    - emacs24-common-non-dfsg
    - sbcl
    - sbcl-doc
    - sbcl-source

- name: Erlang | Download the erlang source
  get_url:
    url: "http://erlang.org/download/otp_src_{{erlang_version}}.tar.gz"
    dest: "/tmp/otp_src_{{erlang_version}}.tar.gz"
  register: erlang_downloaded

- name: Erlang | Unpack the compressed erlang source
  command: tar -xvzf /tmp/otp_src_{{erlang_version}}.tar.gz chdir=/tmp creates=/tmp/otp_src_{{erlang_version}}/README.md
  when: erlang_downloaded.changed

- name: Erlang | Build erlang from source - pt. 1 (configure)
  command: "./configure chdir=/tmp/otp_src_{{erlang_version}}"
  when: erlang_downloaded.changed

- name: Erlang | Build erlang from source - pt. 2 (make)
  command: "make chdir=/tmp/otp_src_{{erlang_version}}"
  when: erlang_downloaded.changed

- name: Erlang | Build erlang from source - pt. 3 (make install)
  sudo: true
  command: "make install chdir=/tmp/otp_src_{{erlang_version}}"
  when: erlang_downloaded.changed
